// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace ConsumeApis.Clases
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using ConsumeApis;
    using System.Net.Http;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    public partial class Carreras
    {
        [JsonProperty("codigocarrera")]
        public string Codigo_Carrera { get; set; }

        [JsonProperty("nombreCarrera")]
        public string Nombre_Carrera { get; set; }


    }
    public partial class Carreras
    {
        public static List<Carreras> FromJson(string json) => JsonConvert.DeserializeObject<List<Carreras>>(json, ConsumeApis.Clases.Converter.Settings);
    }
    public static class SerializeC
    {
        public static string ToJson(this Carreras self) => JsonConvert.SerializeObject(self, ConsumeApis.Clases.Converter.Settings);
    }

    internal static class ConverterC
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
