// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace CarreraInsertar
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class carrerainsertar
    {
        [JsonProperty("codigocarrera")]
        public string Codigocarrera { get; set; }

        [JsonProperty("nombreCarrera")]
        public string NombreCarrera { get; set; }
    }

    public partial class carrerainsertar
    {
        public static List<carrerainsertar> FromJson(string json) => JsonConvert.DeserializeObject<List<carrerainsertar>>(json, CarreraInsertar.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this carrerainsertar self) => JsonConvert.SerializeObject(self, CarreraInsertar.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
