// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace QuickType2
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class cursoActualiza
    {
        [JsonProperty("codigo_Curso")]
        public string CodigoCurso { get; set; }

        [JsonProperty("nombre_Curso")]
        public string NombreCurso { get; set; }

        [JsonProperty("codigo_Carrera")]
        public string CodigoCarrera { get; set; }
    }

    public partial class cursoActualiza
    {
        public static cursoActualiza FromJson(string json) => JsonConvert.DeserializeObject<cursoActualiza>(json, QuickType2.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this cursoActualiza self) => JsonConvert.SerializeObject(self, QuickType2.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
