// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace ConsumeApis
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using pruebaconsumeAPI;

    public partial class estudiante2
    {
        [JsonProperty("tipo_ID")]
        public string TipoId { get; set; }

        [JsonProperty("identificacion")]
        public string Identificacion { get; set; }

        [JsonProperty("nombre")]
        public string Nombre { get; set; }

        [JsonProperty("primer_Apellido")]
        public string PrimerApellido { get; set; }

        [JsonProperty("segundo_apellido")]
        public string SegundoApellido { get; set; }

        [JsonProperty("fecha_Nacimiento")]
        public string FechaNacimiento { get; set; }

    
    }

    public partial class estudiante2
    {
        public static List<estudiante2> FromJson(string json) => JsonConvert.DeserializeObject<List<estudiante2>>(json, ConsumeApis.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this estudiante2 self) => JsonConvert.SerializeObject(self, ConsumeApis.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
