// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace pruebaconsumeAPI
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using ConsumeApis;
    using System.Net.Http;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class estudiante
    {
      public const string BASE_URL = "http://localhost:64612/api/Estudiantes";
      
        [JsonProperty("tipo_ID")]
        public string TipoId { get; set; }

        [JsonProperty("identificacion")]
        public string Identificacion { get; set; }

        [JsonProperty("nombre")]
        public string Nombre { get; set; }

        [JsonProperty("primerApellido")]
        public string PrimerApellido { get; set; }

        [JsonProperty("segundoApellido")]
        public string SegundoApellido { get; set; }

        [JsonProperty("fechaNacimiento")]
        public string FechaNacimiento { get; set; }

        [JsonProperty("correoEle")]
        public string CorreoEle { get; set; }

        [JsonProperty("numerosTelefono")]
        public string NumerosTelefono { get; set; }

    }


    public partial class estudiante
    {
        public static List<estudiante> FromJson(string json) => JsonConvert.DeserializeObject<List<estudiante>>(json, pruebaconsumeAPI.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this estudiante self) => JsonConvert.SerializeObject(self, pruebaconsumeAPI.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }



}


