// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using claseconsume;
//
//    var periodoconsulta = Periodoconsulta.FromJson(jsonString);

namespace claseconsume
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Periodoconsulta
    {
        [JsonProperty("anno")]
        public long Anno { get; set; }

        [JsonProperty("fecha_Inicio")]
        public DateTimeOffset FechaInicio { get; set; }

        [JsonProperty("fecha_Fin")]
        public DateTimeOffset FechaFin { get; set; }

        [JsonProperty("numeroPeriodo")]
        public long NumeroPeriodo { get; set; }

        [JsonProperty("estado")]
        public string Estado { get; set; }
    }

    public partial class Periodoconsulta
    {
        public static List<Periodoconsulta> FromJson(string json) => JsonConvert.DeserializeObject<List<Periodoconsulta>>(json, claseconsume.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Periodoconsulta self) => JsonConvert.SerializeObject(self, claseconsume.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
